### ISSUE TITLE
Write amplification details?

### ISSUE THREAD

**Issue by benwills** [manticoresoftware/columnar#1]
As a longtime user of Sphinx/Manticore, I'm really excited you guys are working on this. Thank you so much.

I love that you're designing the data structures and implementation in a way that requires so little memory. I've done some testing of mmap()ing disk-based array performance, and I'm really glad to see this project taking advantage of modern storage capabilities.

The question I have is around disk write amplification. RocksDB, LevelDB, and Clickhouse all suffer from pretty high write aplification. As someone who has had catastrophic failure from write amplifications like this, I'm extra cautious.

Do you have benchmarks/an overview of how the data is written to disk, and how it compares to other engines? If the implementation is straightforward and you'd rather point me there, is there somewhere in the code you could point me toward?

Again, I'm really excited you're working on this. I really love what you've all done in the last three years and feel that Manticore is such a far under-appreciated application. The engineering you're all doing is fantastic. Thank you.

**Comment by sanikolaev** [comment]
Hello @benwills 

Sorry for the delay and thank you for your warm words.

> Do you have benchmarks/an overview of how the data is written to disk, and how it compares to other engines? If the implementation is straightforward and you'd rather point me there, is there somewhere in the code you could point me toward?

We don't have write amplifications benchmarks yet, and speaking about that, to make fair benchmarks first of all it makes sense to wait until the columnar library is supported by real-time indexes as now it's only available for plain indexes. We are working on that right now.

The RT index in columnar mode will mostly work the same way it works in the row-wise mode (in terms of the extra write amplification it can bring) and it's quite close to the LSM, shortly speaking:
* inserts and replaces are accumulated in a RAM chunk backed by a binary log
* upon `rt_mem_limit` threshold the RAM chunk is flushed to disk
* manual or automatic (work in progress) OPTIMIZE does compaction, leaving `# of CPU cores * 2` chunks by default. The chunks are merged in pairs from smaller to bigger.

There are 2 more things worth mentioning with regard to the columnar library itself:
* it doesn't support UPDATEs
* when it makes columns files (`.spc`) it first makes them one file per a column merging them all to one at a later stage. This is one of the clear write amplifications which happens. We are still discussing what should be a default for that as w/o that merging there's a risk of file handlers overflow (or the need to implement more complex way of dealing with file handlers) but it shouldn't be a big deal to at least make it configurable.
* it doesn't support secondary indexes yet, which can also affect write amplification

> As someone who has had catastrophic failure from write amplifications like this, I'm extra cautious.

I'll appreciate it if you share more details on your use case, so we can take it into consideration.
