### ISSUE TITLE
lib_manticore_columnar wrong path

### ISSUE THREAD

**Issue by webigorkiev** [manticoresoftware/columnar#15]
Hello
Under Debian 10

After Compiling Manticore columnar lib install in /share/manticore/modules
But manticore not found it

Then I copy libs to 
/usr/share/manticore/modules/lib_manticore_columnar.so

And everything worked
Manticore 5.0.3 cff178311@220703 dev (columnar 1.16.1 637ddc6@220727) (secondary 1.16.1 637ddc6@220727)

Maybe it's a bug with the library directory

**Comment by sanikolaev** [comment]
@webigorkiev can you comment why you've closed the issue?

**Comment by webigorkiev** [comment]
In new version Manticore 6.0.2 89c7a5139@230210 (columnar 2.0.0 a7c703d@230130) (secondary 2.0.0 a7c703d@230130)
In my environment, the code build was successful.
