### ISSUE TITLE
Can publish to homebrew?

### ISSUE THREAD

**Issue by cevin** [manticoresoftware/columnar#29]
Can't experience using columnar on macOS

**Comment by sanikolaev** [comment]
How did you install Manticore? Did you follow this instruction

<img width="1509" alt="image" src="https://github.com/manticoresoftware/columnar/assets/28719845/dd1067aa-a797-4e84-8152-9a922b52c910">

?

**Comment by cevin** [comment]
> How did you install Manticore? Did you follow this instruction
> 
> <img alt="image" width="1509" src="https://user-images.githubusercontent.com/28719845/262557091-dd1067aa-a797-4e84-8152-9a922b52c910.png">
> ?

no, just `brew install manticore`,  i'll try this.
