### ISSUE TITLE
columnar: integrate streamvbyte library

### ISSUE THREAD

**Issue by githubmanticore** [manticoresoftware/columnar#30]
streamvbyte is a codec that uses AVX2, it is included in the fastpfor library. However, most recent version is developed as a separate library, https://github.com/lemire/streamvbyte. We need to integrate that library with MCL as this will allow us to use a most recent version of the codec and use a version of it that has built-in differential coding. Using that built-in version should be faster than using external code to calc deltas and inverse deltas. The downside is that it requires implementing a specialized codec in the MCL.

**Comment by glookka** [comment]
Done in 52c59922
