### ISSUE TITLE
Update deps in the daemon after CI

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/columnar#32]
The task is to make an automated PR in the daemon repo to update deps.txt if the columnar commit passes tests. Exactly like it's done in the Buddy repo.

**Comment by donhardman** [comment]
Here is the pull request: https://github.com/manticoresoftware/columnar/pull/33
Updated deps in manticoresearch: https://github.com/manticoresoftware/manticoresearch/pull/1449
