### ISSUE TITLE
incorporate autotag into CI

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/columnar#41]
Currently when we sync from gitlab to github [this function](https://github.com/manticoresoftware/columnar/blob/975172c5920292921f503f6e49b4ffde26624626/gitsync_columnar.sh#L5-L29) is called which creates the needed tag and propagates it further. When we sync from github to gitlab it doesn't happen - https://github.com/manticoresoftware/columnar/blob/975172c5920292921f503f6e49b4ffde26624626/.github/workflows/mirror.yml#L28-L33

The task is to fix it.

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/columnar/commit/5578d8326e68d627ae6c1c75d120c91877f4d2aa

**Comment by sanikolaev** [comment]
Please fix the issues https://github.com/manticoresoftware/columnar/commit/5578d8326e68d627ae6c1c75d120c91877f4d2aa

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/columnar/pull/45

I didn't use there `--follow-tags` flag, because it doesn't work property .
