### ISSUE TITLE
Is it possible to achieve additional effects in plain mode?

### ISSUE THREAD

**Issue by sangensong** [manticoresoftware/columnar#5]

**Comment by sanikolaev** [comment]
Hi. I didn't quite understand the issue. What additional effects do you mean?

**Comment by sangensong** [comment]
For example. I have a `plain mode` index P. The P's data comes from logs. it contains a lot of data. 

As time goes by, more and more log data are generated. I want to add the new generate log data into the index P without deal the old logs.

**Comment by sangensong** [comment]
English is not my native language, I hope the author can understand

**Comment by sangensong** [comment]
The reason that i don't want to use rt mode is that the plain mode's speed is really cool.

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
> As time goes by, more and more log data are generated. I want to add the new generate log data into the index P 
 
What you are looking for is probably that Manticore Search real-time indexes would support the Manticore Columnar Library. We are working on it, the alpha version has been already implemented, we hope to have it ready for testing within a month or so.
