### ISSUE TITLE
distributed index can not handle knn queries

### ISSUE THREAD

**Issue by tomatolog** [manticoresoftware/columnar#55]
seems all knn related data is not send to agent that is why agents of the distributed index replies with the error
```
select id, knn_dist() from distr where knn ( image_vector, 5, (0.286569,-0.031816,0.066684,0.032926) );
ERROR 1064: table distr: agent ip: remote query error: table test: KNN_DIST() is only allowed for KNN() queries
```

**Comment by glookka** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/fb447b26486a9297dd4d68a92336bfeb00a4e79b
