### ISSUE TITLE
mysqlimport support?

### ISSUE THREAD

**Issue by sangensong** [manticoresoftware/columnar#6]
Does your project support `mysqlimport`? I want to import the csv file into a table in `rt` mode through [mysqlimport](https://dev.mysql.com/doc/refman/8.0/en/mysqlimport.html)

**Comment by sanikolaev** [comment]
mysqlimport is just a wrapper for `LOAD DATA`. Manticore doesn's support `LOAD DATA`, but it supports making a plain index from a csv and then attaching it to a real-time index with command `ATTACH` (see https://mnt.cr/attach). 
But anyway Manticore Columnar Library is not supported in RT indexes yet.

**Comment by sangensong** [comment]
Thansk
